const VUE3_STATE_MANAGE_VUEX = "vuex";
const VUE3_STATE_MANAGE_PINIA = "pinia";
const VUE3_STATE_MANAGE = [VUE3_STATE_MANAGE_VUEX, VUE3_STATE_MANAGE_PINIA];

module.exports = {
  VUE3_STATE_MANAGE,
  VUE3_STATE_MANAGE_VUEX,
  VUE3_STATE_MANAGE_PINIA,
};
